info:
  stage: admin manage

spring:
  application:
    name: spring-boot-admin
  boot:
    admin:
      url: http://localhost:18080
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,hystrix.stream,turbine.stream
  cloud:
    config:
      name: sample
      uri: http://localhost:11088/

endpoints:
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11011/eureka/

logging:
  level:
    org.springframework: INFO
    cc.sion: debug

server:
 port: 18080