info:
  stage: admin manage

spring:
  application:
    name: spring-boot-admin
  cloud:
    config:
      name: sample
      uri: http://localhost:11088/

# tag::configuration-ui-hystrix[]
spring.boot.admin.routes.endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,hystrix.stream,turbine.stream
# end::configuration-ui-hystrix[]


endpoints:
  health:
    sensitive: false


# tag::configuration-eureka[]
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:11011/eureka/
# end::configuration-eureka[]


server:
 port: 18080