info:
  stage: admin manage

spring:
  application:
    name: spring-boot-admin
  cloud:
    config:
      name: sample
      uri: http://localhost:11088/
  boot:
    admin:
      url:  http://localhost:${server.port}
      routes:
        endpoints: metrics

endpoints:
  health:
    sensitive: false


# tag::configuration-eureka[]
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:11011/eureka/
# end::configuration-eureka[]


server:
 port: 18080