server:
  port: 11011

eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/