eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11011/eureka/

logging:
  level:
    org.springframework: debug
    cc.sion: debug

spring:
  thymeleaf:
    cache:  true
    mode: html