info:
  stage: web

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11011/eureka/

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled:  false
        isolation:
          thread:
            timeoutInMilliseconds:  10000
  threadpool:
    default:
      coreSize: 50
      maxQueueSize: 100
      queueSizeRejectionThreshold: 50
