info:
  stage: say demo
  description: include spring-boot-admin client

# tag::configuration-eureka[]
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:11011/eureka/
# end::configuration-eureka[]