# tag::configuration-eureka[]
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:11011/eureka/
# end::configuration-eureka[]

info:
  description: exclude spring-boot-admin client

logging:
  level:
    org.springframework: INFO
    cc.sion: debug
    de.codecentric.boot.admin: debug
