# tag::configuration-eureka[]
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:11011/eureka/
# end::configuration-eureka[]

info:
  description: exclude spring-boot-admin client

netflix:
  atlas:
    uri:  http://localhost:7101/api/v1/publish/
