server:
  port: 11088

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      name: sample

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:11011/eureka/

